<?php

use Illuminate\Database\Seeder;

class PaisSeeder extends Seeder {
    public function run() {
        DB::table('Pais')->delete();
        
        DB::table('Pais')->insert([
            ['idPais' => 0, 'nombre' => 'Seleccionar', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 0, 'vigente' => 0],
            ['idPais' => 1, 'nombre' => 'Africa del Sur', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 2, 'nombre' => 'Albania', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 3, 'nombre' => 'Alemania', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 4, 'nombre' => 'Andorra', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 5, 'nombre' => 'Angola', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 6, 'nombre' => 'Antigua y Barbuda', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 7, 'nombre' => 'Antillas Holandesas', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 8, 'nombre' => 'Arabia Saudita', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 9, 'nombre' => 'Argelia', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 10, 'nombre' => 'Argentina', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 11, 'nombre' => 'Armenia', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 12, 'nombre' => 'Aruba', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 13, 'nombre' => 'Australia', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 14, 'nombre' => 'Austria', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 15, 'nombre' => 'Azerbaijan', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 16, 'nombre' => 'Bahamas', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 17, 'nombre' => 'Bahrain', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 18, 'nombre' => 'Bangladesh', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 19, 'nombre' => 'Barbados', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 20, 'nombre' => 'Belarusia', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 21, 'nombre' => 'Belgica', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 22, 'nombre' => 'Belice', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 23, 'nombre' => 'Benin', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 24, 'nombre' => 'Bermudas', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 25, 'nombre' => 'Bolivia', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 26, 'nombre' => 'Bosnia', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 27, 'nombre' => 'Botswana', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 28, 'nombre' => 'Brasil', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 29, 'nombre' => 'Brunei Darussulam', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 30, 'nombre' => 'Bulgaria', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 31, 'nombre' => 'Burkina Faso', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 32, 'nombre' => 'Burundi', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 33, 'nombre' => 'Butan', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 34, 'nombre' => 'Camboya', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 35, 'nombre' => 'Camerun', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 36, 'nombre' => 'Canada', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 37, 'nombre' => 'Cape Verde', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 38, 'nombre' => 'Chad', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 39, 'nombre' => 'Afganistan', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 40, 'nombre' => 'China', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 41, 'nombre' => 'Chipre', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 42, 'nombre' => 'Chile', 'gentilicio_masculino' => 'Chileno', 'gentilicio_femenino' => 'Chilena', 'orden' => 1, 'vigente' => 1],
            ['idPais' => 43, 'nombre' => 'Colombia', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 44, 'nombre' => 'Comoros', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 45, 'nombre' => 'Congo', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 46, 'nombre' => 'Corea del Norte', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 47, 'nombre' => 'Corea del Sur', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 48, 'nombre' => 'Costa de MarfÌl', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 49, 'nombre' => 'Costa Rica', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 50, 'nombre' => 'Croasia', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 51, 'nombre' => 'Cuba', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 52, 'nombre' => 'Dinamarca', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 53, 'nombre' => 'Djibouti', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 54, 'nombre' => 'Dominica', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 55, 'nombre' => 'Ecuador', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 56, 'nombre' => 'Egipto', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 57, 'nombre' => 'El Salvador', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 58, 'nombre' => 'Emiratos Arabes Unidos', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 59, 'nombre' => 'Eritrea', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 60, 'nombre' => 'Eslovenia', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 61, 'nombre' => 'EspaÒa', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 62, 'nombre' => 'Estados Unidos', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 63, 'nombre' => 'Estonia', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 64, 'nombre' => 'Etiopia', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 65, 'nombre' => 'Fiji', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 66, 'nombre' => 'Filipinas', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 67, 'nombre' => 'Finlandia', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 68, 'nombre' => 'Francia', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 69, 'nombre' => 'Gabon', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 70, 'nombre' => 'Gambia', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 71, 'nombre' => 'Georgia', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 72, 'nombre' => 'Ghana', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 73, 'nombre' => 'Granada', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 74, 'nombre' => 'Grecia', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 75, 'nombre' => 'Groenlandia', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 76, 'nombre' => 'Guadalupe', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 77, 'nombre' => 'Guam', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 78, 'nombre' => 'Guatemala', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 79, 'nombre' => 'Guayana Francesa', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 80, 'nombre' => 'Guerney', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 81, 'nombre' => 'Guinea', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 82, 'nombre' => 'Guinea-Bissau', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 83, 'nombre' => 'Guinea Equatorial', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 84, 'nombre' => 'Guyana', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 85, 'nombre' => 'Haiti', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 86, 'nombre' => 'Holanda', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 87, 'nombre' => 'Honduras', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 88, 'nombre' => 'Hong Kong', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 89, 'nombre' => 'Hungria', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 90, 'nombre' => 'India', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 91, 'nombre' => 'Indonesia', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 92, 'nombre' => 'Irak', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 93, 'nombre' => 'Iran', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 94, 'nombre' => 'Irlanda', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 95, 'nombre' => 'Islandia', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 96, 'nombre' => 'Islas Caiman', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 97, 'nombre' => 'Islas Faroe', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 98, 'nombre' => 'Islas Malvinas', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 99, 'nombre' => 'Islas Marshall', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 100, 'nombre' => 'Islas Solomon', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 101, 'nombre' => 'Islas Virgenes Britanicas', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 102, 'nombre' => 'Islas Virgenes (U.S.)', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 103, 'nombre' => 'Israel', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 104, 'nombre' => 'Italia', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 105, 'nombre' => 'Jamaica', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 106, 'nombre' => 'Japon', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 107, 'nombre' => 'Jersey', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 108, 'nombre' => 'Jordania', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 109, 'nombre' => 'Kazakhstan', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 110, 'nombre' => 'Kenia', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 111, 'nombre' => 'Kiribati', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 112, 'nombre' => 'Kuwait', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 113, 'nombre' => 'Kyrgyzstan', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 114, 'nombre' => 'Laos', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 115, 'nombre' => 'Latvia', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 116, 'nombre' => 'Lesotho', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 117, 'nombre' => 'Libano', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 118, 'nombre' => 'Liberia', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 119, 'nombre' => 'Libia', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 120, 'nombre' => 'Liechtenstein', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 121, 'nombre' => 'Lituania', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 122, 'nombre' => 'Luxemburgo', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 123, 'nombre' => 'Macao', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 124, 'nombre' => 'Macedonia', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 125, 'nombre' => 'Madagascar', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 126, 'nombre' => 'Malasia', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 127, 'nombre' => 'Malawi', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 128, 'nombre' => 'Maldivas', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 129, 'nombre' => 'Mali', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 130, 'nombre' => 'Malta', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 131, 'nombre' => 'Marruecos', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 132, 'nombre' => 'Martinica', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 133, 'nombre' => 'Mauricio', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 134, 'nombre' => 'Mauritania', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 135, 'nombre' => 'Mexico', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 136, 'nombre' => 'Micronesia', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 137, 'nombre' => 'Moldova', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 138, 'nombre' => 'Monaco', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 139, 'nombre' => 'Mongolia', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 140, 'nombre' => 'Mozambique', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 141, 'nombre' => 'Myanmar (Burma)', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 142, 'nombre' => 'Namibia', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 143, 'nombre' => 'Nepal', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 144, 'nombre' => 'Nicaragua', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 145, 'nombre' => 'Niger', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 146, 'nombre' => 'Nigeria', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 147, 'nombre' => 'Noruega', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 148, 'nombre' => 'Nueva Caledonia', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 149, 'nombre' => 'Nueva Zealandia', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 150, 'nombre' => 'Oman', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 151, 'nombre' => 'Pakistan', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 152, 'nombre' => 'Palestina', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 153, 'nombre' => 'Panama', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 154, 'nombre' => 'Papua Nueva Guinea', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 155, 'nombre' => 'Paraguay', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 156, 'nombre' => 'Peru', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 157, 'nombre' => 'Polinesia Francesa', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 158, 'nombre' => 'Polonia', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 159, 'nombre' => 'Portugal', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 160, 'nombre' => 'Puerto Rico', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 161, 'nombre' => 'Qatar', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 162, 'nombre' => 'Reino Unido', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 163, 'nombre' => 'Republica Centroafricana', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 164, 'nombre' => 'Republica Checa', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 165, 'nombre' => 'Republica Democratica del Congo', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 166, 'nombre' => 'Republica Dominicana', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 167, 'nombre' => 'Republica Eslovaca', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 168, 'nombre' => 'Reunion', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 169, 'nombre' => 'Ruanda', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 170, 'nombre' => 'Rumania', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 171, 'nombre' => 'Rusia', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 172, 'nombre' => 'Sahara', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 173, 'nombre' => 'Samoa', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 174, 'nombre' => 'San Cristobal-Nevis (St. Kitts)', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 175, 'nombre' => 'San Marino', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 176, 'nombre' => 'San Vincente y las Granadinas', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 177, 'nombre' => 'Santa Helena', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 178, 'nombre' => 'Santa Lucia', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 179, 'nombre' => 'Santa Sede (Vaticano)', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 180, 'nombre' => 'Sao Tome & Principe', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 181, 'nombre' => 'Senegal', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 182, 'nombre' => 'Seychelles', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 183, 'nombre' => 'Sierra Leona', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 184, 'nombre' => 'Singapur', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 185, 'nombre' => 'Siria', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 186, 'nombre' => 'Somalia', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 187, 'nombre' => 'Sri Lanka (Ceilan)', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 188, 'nombre' => 'Sudan', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 189, 'nombre' => 'Suecia', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 190, 'nombre' => 'Suiza', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 191, 'nombre' => 'Sur Africa', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 192, 'nombre' => 'Surinam', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 193, 'nombre' => 'Swaziland', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 194, 'nombre' => 'Tailandia', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 195, 'nombre' => 'Taiwan', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 196, 'nombre' => 'Tajikistan', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 197, 'nombre' => 'Tanzania', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 198, 'nombre' => 'Timor Oriental', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 199, 'nombre' => 'Togo', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 200, 'nombre' => 'Tokelau', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 201, 'nombre' => 'Tonga', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 202, 'nombre' => 'Trinidad & Tobago', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 203, 'nombre' => 'Tunisia', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 204, 'nombre' => 'Turkmenistan', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 205, 'nombre' => 'Turquia', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 206, 'nombre' => 'Ucrania', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 207, 'nombre' => 'Uganda', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 208, 'nombre' => 'Union Europea', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 209, 'nombre' => 'Uruguay', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 210, 'nombre' => 'Uzbekistan', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 211, 'nombre' => 'Vanuatu', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 212, 'nombre' => 'Venezuela', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 213, 'nombre' => 'Vietnam', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 214, 'nombre' => 'Yemen', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 215, 'nombre' => 'Yugoslavia', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 216, 'nombre' => 'Zambia', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1],
            ['idPais' => 217, 'nombre' => 'Zimbabwe', 'gentilicio_masculino' => '', 'gentilicio_femenino' => '', 'orden' => 2, 'vigente' => 1]
        ]);
    }
}